apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: codap
  source:
    repoURL: https://github.com/vkharishb/CODAP.git
    targetRevision: main
    path: gitops/manifests/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
