apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dora-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: codap
  source:
    repoURL: https://github.com/<your-github-username>/CODAP.git
    targetRevision: main
    path: dora-metrics-service/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dora-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
