{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "dora-metrics-service.name" . }}
    app.kubernetes.io/part-of: codap
  annotations:
{{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
