apiVersion: v1
kind: Service
metadata:
  name: {{ include "dora-metrics-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dora-metrics-service.name" . }}
    app.kubernetes.io/part-of: codap
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "dora-metrics-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
