apiVersion: v1
kind: Service
metadata:
  name: <app-name>
  namespace: <namespace>
  labels:
    app.kubernetes.io/name: <app-name>
    app.kubernetes.io/part-of: codap
spec:
  selector:
    app.kubernetes.io/name: <app-name>
  ports:
    - name: http
      port: 80
      targetPort: 8080
